services:
  - type: web
    name: cal-web
    plan: standard
    repo: https://github.com/calcom/docker.git
    dockerfilePath: ./Dockerfile.render
    env: docker
    envVars:

      - key: DATABASE_URL
        value: postgresql://agenda_consultorio_cal_com_db_user:Spli4809hfeSVKq5ly31JAWE8s8jBFCH@dpg-d1m8js6mcj7s73a00r6g-a/agenda_consultorio_cal_com_db

      - key: CALENDSO_ENCRYPTION_KEY
        value: secret

      - key: NEXTAUTH_SECRET
        value: secret

      - key: CRON_API_KEY
        value: 0cc0e6c35519bba620c9360cfe3e68d0

